import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { promisify } from "node:util";
import { fileURLToPath } from "node:url";

import { makeTempWorkspace } from "./support/helpers.mjs";

const execFileAsync = promisify(execFile);
const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SCRIPT_PATH = path.join(REPO_ROOT, "skills", "cf-cohesion", "scripts", "dir-population.mjs");

async function writeFiles(root, files) {
  for (const [relativePath, content] of Object.entries(files)) {
    const absolutePath = path.join(root, relativePath);
    await mkdir(path.dirname(absolutePath), { recursive: true });
    await writeFile(absolutePath, content);
  }
}

async function run(root, ...args) {
  const { stdout } = await execFileAsync(process.execPath, [SCRIPT_PATH, root, ...args]);
  return stdout;
}

function row(stdout, dir) {
  return stdout.split("\n").find((line) => line.trim().split(/\s+/)[1] === dir);
}

test("dir-population counts only direct real source files and names each exclusion", async () => {
  const root = await makeTempWorkspace("dir-population-");
  const files = {};
  for (let index = 0; index < 10; index += 1) {
    files[`src/model/unit-${index}.ts`] = `export const value${index} = ${index};\n`;
  }
  Object.assign(files, {
    "src/model/unit-0.test.ts": "test('x', () => {});\n",
    "src/model/unit.spec.tsx": "test('x', () => {});\n",
    "src/model/page.fixture.tsx": "export const fixture = 1;\n",
    "src/model/index.ts": "export * from './unit-0';\nexport { value1 } from './unit-1';\n",
    "src/model/api.gen.ts": "export const generated = 1;\n",
    "src/model/schema.ts": "// Code generated by protoc. DO NOT EDIT.\nexport const schema = 1;\n",
    "src/model/types.d.ts": "declare const x: number;\n",
    "src/model/README.md": "# notes\n",
    "src/model/nested/deep.ts": "export const deep = 1;\n",
    "internal/tui/a_test.go": "package tui\n",
    "internal/tui/a.go": "package tui\n",
    "pkg/__init__.py": "from .core import run\n__all__ = ['run']\n",
    "pkg/core.py": "def run():\n    return 1\n",
    "pkg/test_core.py": "def test_run():\n    pass\n",
  });
  await writeFiles(root, files);

  const stdout = await run(root);
  assert.match(
    row(stdout, "src/model"),
    /^\s+10\s+src\/model\s+\(subfolders with source: 1; excluded: tests 2, fixtures 1, re-exports 1, generated 3\)\s+<-- 10\+$/,
  );
  assert.match(row(stdout, "internal/tui"), /^\s+1\s+internal\/tui\s+\(subfolders with source: 0; excluded: tests 1\)$/);
  assert.match(row(stdout, "pkg"), /^\s+1\s+pkg\s+\(subfolders with source: 0; excluded: tests 1, re-exports 1\)$/);
  assert.doesNotMatch(row(stdout, "src/model/nested"), /<--/);
});

test("dir-population recognizes test and generated conventions across languages", async () => {
  const root = await makeTempWorkspace("dir-population-languages-");
  await writeFiles(root, {
    // Real sources, one per language, in one directory.
    "src/app.java": "class App {}\n",
    "src/app.kt": "class App\n",
    "src/app.swift": "struct App {}\n",
    "src/app.cs": "class App {}\n",
    "src/app.php": "<?php class App {}\n",
    "src/app.rb": "class App; end\n",
    "src/app.ex": "defmodule App do end\n",
    "src/app.dart": "class App {}\n",
    "src/app.cpp": "int main() {}\n",
    "src/app.rs": "pub fn run() {}\n#[cfg(test)]\nmod tests {}\n",
    "src/label.ts": "export const label = 'Auto-generated name';\n",
    // Tests by file name.
    "src/AppTest.java": "class AppTest {}\n",
    "src/AppTests.swift": "final class AppTests {}\n",
    "src/AppSpec.scala": "class AppSpec\n",
    "src/AppTest.php": "<?php class AppTest {}\n",
    "src/app_spec.rb": "describe App do end\n",
    "src/app_test.exs": "defmodule AppTest do end\n",
    "src/app_test.dart": "void main() {}\n",
    "src/app_unittest.cc": "TEST(App, Runs) {}\n",
    "src/conftest.py": "import pytest\n",
    "src/tests.rs": "use super::*;\n",
    "src/login.cy.ts": "it('logs in', () => {});\n",
    // Generated by file name or header comment.
    "src/Form.Designer.cs": "partial class Form {}\n",
    "src/model.g.dart": "part of 'model.dart';\n",
    "src/api_gen.go": "package api\n",
    "src/schema.py": "# @generated by tooling\nSCHEMA = {}\n",
    // Tests by folder.
    "Sources/Tests/AppTests.swift": "final class AppTests {}\n",
    "MyApp.Tests/AppFacts.cs": "class AppFacts {}\n",
    "src/application/outline_tests/rust.rs": "use super::*;\n",
    "app/src/androidTest/MainTest.kt": "class MainTest\n",
    "src/features/abTest/variant.ts": "export const variant = 'a';\n",
  });

  const stdout = await run(root);
  assert.match(row(stdout, "src"), /^\s+11\s+src\s+\(subfolders with source: 1; excluded: tests 11, generated 4\)\s+<-- 10\+$/);
  for (const dir of ["Sources/Tests", "MyApp.Tests", "src/application/outline_tests", "app/src/androidTest"]) {
    assert.equal(row(stdout, dir), undefined, dir);
  }
  assert.match(row(stdout, "src/features/abTest"), /^\s+1\s+src\/features\/abTest\s/);
});

test("dir-population skips tracked files missing from the working tree", async () => {
  const root = await makeTempWorkspace("dir-population-missing-");
  await writeFiles(root, { "src/a.ts": "export const a = 1;\n", "src/b.ts": "export const b = 1;\n" });
  const git = (...args) => execFileAsync("git", ["-C", root, ...args]);
  await git("init", "-q");
  await git("add", ".");
  await rm(path.join(root, "src", "b.ts"));

  assert.match(row(await run(root), "src"), /^\s+1\s+src\s/);
});

test("dir-population keeps a module that re-exports and also declares code", async () => {
  const root = await makeTempWorkspace("dir-population-mixed-");
  await writeFiles(root, {
    "src/index.ts": "export * from './a';\nexport function main() {\n  return 1;\n}\n",
    "src/a.ts": "export const a = 1;\n",
  });

  assert.match(row(await run(root), "src"), /^\s+2\s+src\s+\(subfolders with source: 0\)$/);
});

test("dir-population limits the inventory to --include paths", async () => {
  const root = await makeTempWorkspace("dir-population-include-");
  await writeFiles(root, {
    "src/a.ts": "export const a = 1;\n",
    "lib/b.ts": "export const b = 1;\n",
  });

  const stdout = await run(root, "--include", "lib");
  assert.ok(row(stdout, "lib"));
  assert.equal(row(stdout, "src"), undefined);
});

test("dir-population prints usage", async () => {
  const { stdout } = await execFileAsync(process.execPath, [SCRIPT_PATH, "--help"]);
  assert.match(stdout, /Usage:/);
  assert.match(stdout, /read a candidate directory's files before deciding/);
});
